/**
 * ============================================================
 * UniBot — Intent training data (English)
 * ------------------------------------------------------------
 * Each intent lists example utterances used to train the NLP.js
 * classifier. The classifier generalises from these, so users do
 * not have to phrase a question exactly as written here.
 *
 *   data.*   answered live from MongoDB, scoped to the asker
 *   faq.*    answered from the static `answers` map below
 *   chat.*   small talk
 *   None     out-of-domain, triggers the fallback reply
 *
 * Phrasings deliberately cover all three roles, because a
 * coordinator and an admin ask the same question differently
 * from a student ("assigned to me" vs "my complaints").
 * ============================================================
 */

const intents = {
  /* ============================================================
     COMPLAINT LOOKUP
     ============================================================ */

  // General "where does it stand"
  'data.complaint.status': [
    'what is the status of my complaint',
    'status of my complaint',
    'my complaint status',
    'check my complaint status',
    'where is my complaint',
    'what happened to my complaint',
    'any update on my complaint',
    'update on my complaints',
    'tell me about my complaint',
    'show me my complaint status',
    'complaint status please',
    'progress of my complaint',
    'track my complaint',
    'whats happening with my complaint',
    'give me an update',
    'status update please',
    'how is my complaint going',
    'what is the current status',
    'status of the complaints assigned to me',
    'what is the status of this complaint',
    'current position of my complaint',
    'where does my complaint stand',
    'can you check on my complaint',
    'check on my complaint for me',
    'please check my complaint',
    'any news on my complaint',
    'any progress on my complaint',
    'how far along is my complaint',
    'what stage is my complaint at',
    'whats the latest with my complaint',
    'fill me in on my complaint',
    'where has my complaint reached',
    'where has my complaint got up to',
    'how is my complaint doing',
    'where is my complaint right now',
    'what point is my complaint at',
    'has anything changed on my complaint',
    'has there been any movement on it',
    'has anything progressed',
    'has anything happened with it',
    'i want to know about my complaint',
    'i would like to know about my complaint',
    'tell me where my complaint stands',
    'i need an update on my complaint',
  ],

  // Yes/no framing — deserves a direct yes or no answer
  'data.complaint.check': [
    'is my complaint resolved',
    'has my complaint been resolved',
    'is it resolved',
    'is it resolved yet',
    'has it been fixed',
    'is my complaint fixed yet',
    'did they fix my complaint',
    'has my issue been sorted',
    'is my problem solved',
    'has my complaint been closed',
    'is my complaint still open',
    'is it done yet',
    'has anyone looked at my complaint',
    'did anyone work on my complaint',
    'is my complaint still pending',
    'has it been assigned yet',
    'was my complaint accepted',
    'is my complaint approved',
    'is that one finished',
    'has that been dealt with',
    'are all my complaints resolved',
    'are they all resolved',
    'is everything resolved',
    'have they all been resolved',
    'is everything of mine closed',
    'is that one closed',
    'is that complaint closed',
    'has that complaint been closed',
    'is that complaint sorted',
    'is that resolved now',
    'is that complaint done now',
    'is it resolved or not',
    'has it been fixed or not',
    'has my issue been sorted or not',
    'is my complaint resolved or still open',
    'did my complaint get fixed',
    'did it get fixed',
    'was it fixed in the end',
    'did they fix it eventually',
    'did it get sorted in the end',
    'tell me if my complaint is done',
    'tell me whether my complaint is resolved',
    'let me know if it is done',
    'complaint resolved or not',
    'resolved or not',
    'just tell me if it is done',
  ],

  // Referring to a complaint by its subject matter
  'data.complaint.about': [
    'what about my complaint for the course registration',
    'what about my complaint about the wifi',
    'what about my hostel complaint',
    'tell me about my fee complaint',
    'what happened to my complaint about the library',
    'status of my complaint regarding the exam',
    'my complaint about the bus',
    'the complaint i submitted about the lab',
    'what about the one regarding my result',
    'my complaint related to the hostel water',
    'the one about the projector',
    'what happened with my transport complaint',
    'update on my complaint about the air conditioning',
    'my complaint concerning the fee challan',
    'what about my complaint for the scholarship',
    'the complaint i filed about attendance',
    'what happened to my complaint about the mess food',
    'what happened to my complaint about the food',
    'what about my complaint on the mess',
  ],

  'data.complaint.list': [
    'show my complaints',
    'list my complaints',
    'what complaints do i have',
    'see all my complaints',
    'my complaints',
    'show me all complaints',
    'display my complaints',
    'view my complaints',
    'what have i submitted',
    'complaints i submitted',
    'show all the complaints',
    'give me my complaint list',
    'list all complaints',
    'show me the complaints assigned to me',
    'what is assigned to me',
    'list the complaints i am handling',
    'show my cases',
    'what am i handling right now',
    'show me everything',
    'list everything i have filed',
    'what do i have open with you',
    'bring up all my complaints',
    'pull up my complaints',
    'let me see my complaints',
    'i want to see my complaints',
    'what is on my record',
    'take me through my complaints',
    'can i see everything i have submitted',
    'can i see everything i submitted',
    'let me see everything i have submitted',
    'show me everything i have submitted',
  ],

  'data.complaint.count': [
    'how many complaints do i have',
    'how many complaints have i submitted',
    'total complaints',
    'number of complaints',
    'count my complaints',
    'how many complaints are there',
    'how many complaints in total',
    'total number of complaints',
    'how many are resolved',
    'how many of my complaints are resolved',
    'how many are still pending',
    'how many complaints are pending',
    'how many were rejected',
    'how many complaints are assigned to me',
    'how many are in progress',
    'how many complaints did i file',
    'give me the total count',
    'how many cases do i have',
    'how many complaints does the system have',
    'how many complaints have been resolved so far',
    'total number of complaints i have',
    'whats my total',
    'give me my total count',
    'what is my complaint total',
    'how many altogether',
    'how many in total for me',
    'how many have i raised in total',
    'how many have i lodged so far',
    'how many did i submit altogether',
    'how many have i filed altogether',
    'how many complaints have i raised',
    'what is my caseload',
    'how big is my caseload',
    'total complaints in the system',
    'total number in the system',
    'how many are in the system',
  ],

  'data.complaint.pending': [
    'which complaints are still pending',
    'show pending complaints',
    'show my pending complaints',
    'show me my pending complaints',
    'list my pending complaints',
    'view pending complaints',
    'what is still unresolved',
    'unresolved complaints',
    'pending complaints',
    'complaints not resolved',
    'what is still open',
    'open complaints',
    'complaints waiting for action',
    'anything still pending',
    'my pending complaints',
    'still pending complaints',
    'which of my complaints are not done',
    'what is left to do',
    'which cases are still open',
    'what is still outstanding',
    'anything outstanding',
    'what is not finished',
    'anything not done yet',
    'anything not finished',
    'which are not closed',
    'what remains open',
    'what has not been completed',
    'is anything still not finished',
    'what have i got outstanding',
    'what do i have outstanding',
    'anything outstanding for me',
    'what is outstanding',
  ],

  'data.complaint.resolved': [
    'which complaints are resolved',
    'show resolved complaints',
    'show my resolved complaints',
    'show me my resolved complaints',
    'list my resolved complaints',
    'view resolved complaints',
    'my resolved complaints',
    'what has been resolved',
    'completed complaints',
    'resolved complaints',
    'finished complaints',
    'closed complaints',
    'what got fixed',
    'which of my complaints are resolved',
    'display resolved complaints',
    'which ones have been completed',
    'which of mine have been sorted out',
    'which have been sorted',
    'what has been sorted out',
    'show me the finished ones',
    'which ones are done and dusted',
    'have any of mine been sorted',
    'which of mine are sorted',
    'anything of mine sorted out',
    'which ones got sorted',
    'have any been resolved for me',
    'show all the done ones',
    'list everything completed',
    'show what is complete',
    'show everything already handled',
    'show the ones that are done',
    'which complaints are done',
    'list what is done',
    'show all done complaints',
    'show the finished complaints',
    'which complaints are finished',
    'show me everything that is finished',
    'list my completed cases',
    'list my completed complaints',
    'show my completed cases',
    'show everything that is resolved',
    'show me all that is resolved',
    'everything that is resolved',
  ],

  'data.complaint.rejected': [
    'show my rejected complaints',
    'which complaints were rejected',
    'list rejected complaints',
    'rejected complaints',
    'what was rejected',
    'why was my complaint rejected',
    'which of my complaints got rejected',
    'show me the rejected ones',
    'was anything rejected',
    'my declined complaints',
    'reason for rejection of my complaint',
    'did any of mine get turned down',
    'were any of my complaints turned down',
    'which of mine were declined',
    'anything of mine rejected',
    'have any been turned down',
    'were any thrown out',
    'did any get thrown out',
    'was anything dismissed',
    'any of mine refused',
    'has anything been thrown out',
  ],

  'data.complaint.latest': [
    'what is my latest complaint',
    'my most recent complaint',
    'last complaint i submitted',
    'newest complaint',
    'my recent complaint',
    'latest complaint status',
    'the last one i filed',
    'what did i submit most recently',
    'show me the newest complaint',
    'most recent case assigned to me',
  ],

  'data.complaint.oldest': [
    'what is my oldest complaint',
    'which complaint is the oldest',
    'oldest pending complaint',
    'what has been waiting the longest',
    'which one has been open the longest',
    'show me the oldest case',
    'longest pending complaint',
    'which complaint is taking the longest',
    'what is my oldest unresolved complaint',
    'which complaint is taking forever',
    'what is taking the longest',
    'which one is dragging on',
    'what has been waiting the longest',
    'which is the slowest complaint',
    'what is stuck the longest',
    'which is the most overdue',
    'what is most overdue',
    'which one is overdue',
    'which has been pending the longest',
    'which is running late',
  ],

  'data.complaint.urgent': [
    'which complaint is most urgent',
    'show urgent complaints',
    'what is high priority',
    'most urgent complaint',
    'show me high priority complaints',
    'which ones are urgent',
    'list the urgent cases',
    'what needs immediate attention',
    'anything critical',
    'show me the important ones',
    'which complaints are marked urgent',
    'what are the top priority ones',
    'top priority complaints',
    'which are top priority',
    'show me top priority items',
    'what is the highest priority right now',
    'which one is most urgent',
    'which one is the most urgent',
    'which of them is most urgent',
    'which complaint needs attention first',
    'anything urgent for me',
  ],

  'data.complaint.handler': [
    'who is handling my complaint',
    'who is working on my complaint',
    'which coordinator has my complaint',
    'who is responsible for my complaint',
    'who was it assigned to',
    'which department is handling it',
    'who is looking into this',
    'who is in charge of my complaint',
    'which staff member has my case',
    'who will resolve my complaint',
  ],

  'data.complaint.duration': [
    'how long has my complaint been open',
    'how many days has it been pending',
    'when will my complaint be resolved',
    'how long will it take to resolve my complaint',
    'how old is my complaint',
    'how long have i been waiting',
    'when will it be fixed',
    'how much longer will it take',
    'how many days since i submitted it',
    'how long has this been in progress',
    'how much longer do i wait',
    'how much more time will it take',
    'how many more days for my complaint',
    'when can i expect my complaint to be done',
    'how long more for my complaint',
    'is my complaint going to take much longer',
  ],

  'data.complaint.next': [
    'what should i do next',
    'what happens now',
    'what is the next step',
    'what do i do now',
    'anything i need to do',
    'is there any action required from me',
    'what should i do about my complaint',
    'do i need to do anything',
    'what happens after this',
    'what is expected from me now',
    'do i have to do anything more',
    'is there anything more for me to do',
    'do i need to take any action',
    'is any action required from my side',
    'anything else i must do',
  ],

  // Full activity history of a complaint
  'data.complaint.timeline': [
    'what has happened with my complaint',
    'show me the history of my complaint',
    'what updates have there been',
    'show the progress history',
    'what has been done so far',
    'give me the full history',
    'what steps have been taken',
    'timeline of my complaint',
    'show activity on my complaint',
    'what has happened so far',
    'show me all the updates',
    'walk me through what happened',
    'what actions were taken on it',
    'history of this complaint',
    'what has been done on my complaint',
    'what work has been done on it',
    'what actions have been taken on my complaint',
    'what has been done so far on it',
  ],

  // Category / department breakdown of the asker's own complaints
  'data.complaint.breakdown': [
    'what do i complain about most',
    'breakdown of my complaints',
    'what categories have i used',
    'which category do i complain about most',
    'show me a breakdown',
    'what types of complaints have i submitted',
    'group my complaints by category',
    'what kind of complaints do i have',
    'split my complaints by category',
    'summarise my complaints by type',
    'which departments have my complaints',
    'breakdown by category',
  ],

  // Which complaints are waiting for the student's rating
  'data.complaint.feedback': [
    'which complaints can i rate',
    'do i need to give feedback',
    'have i rated my complaints',
    'which ones need my feedback',
    'can i still rate anything',
    'what feedback have i given',
    'which are waiting for my rating',
    'do i owe any feedback',
    'have i left any reviews',
    'which ones have i not rated',
    'is there anything for me to rate',
    'is there anything i need to score',
    'anything left for me to score',
    'do i still need to rate anything',
    'which ones are awaiting my rating',
    'anything pending my review score',
    'which of mine are awaiting a rating from me',
    'which of mine need a rating from me',
    'what is awaiting a rating from me',
  ],

  'data.notifications': [
    'do i have any notifications',
    'show my notifications',
    'any new updates for me',
    'check notifications',
    'any messages for me',
    'unread notifications',
    'what did i miss',
    'any alerts for me',
    'show recent updates',
    'anything new for me',
    'is there anything new i should see',
    'any new alerts',
    'have i got new notifications',
    'anything i have not seen yet',
    'show me my inbox',
  ],

  /* ============================================================
     ANALYTICS — mainly admin and coordinator
     ============================================================ */

  'data.stats.departments': [
    'which department has the most complaints',
    'complaints by department',
    'which department has the worst rating',
    'department wise breakdown',
    'which department is performing best',
    'show department statistics',
    'how are the departments doing',
    'which department gets the most complaints',
    'department performance',
    'breakdown by department',
    'which department has the lowest satisfaction',
    'which section gets the most complaints',
    'which area receives the most complaints',
    'which unit has the most complaints',
    'which office gets complained about most',
  ],

  'data.stats.coordinators': [
    'which coordinator has the best rating',
    'coordinator performance',
    'how are the coordinators doing',
    'which coordinator is rated highest',
    'show coordinator statistics',
    'which coordinator has the most complaints',
    'coordinator wise breakdown',
    'who is the best performing coordinator',
    'which coordinator has the lowest rating',
    'how am i performing',
    'what is my rating',
    'how is my performance',
    'what do students think of my work',
    'what do students think of me',
    'what feedback have i received',
    'how do students rate me',
  ],

  'data.stats.performance': [
    'what is the average resolution time',
    'how long does it take on average',
    'what is the average rating',
    'overall satisfaction score',
    'show me the overall statistics',
    'system performance summary',
    'give me an overview',
    'how is the system doing overall',
    'average feedback score',
    'what is the overall performance',
    'summary of everything',
    'what is the mean resolution time',
    'what is the mean time to resolve',
    'average time to resolve complaints',
    'what is the average turnaround time',
    'overall system summary',
    'give me the headline numbers',
    'how efficient is the system',
    'what is the average turnaround',
    'what is our turnaround time',
    'how fast do we resolve things',
    'how quickly do we close complaints',
  ],

  'data.stats.unassigned': [
    'how many complaints are waiting for review',
    'what needs to be assigned',
    'show unassigned complaints',
    'which complaints are not assigned yet',
    'how many are awaiting approval',
    'what is waiting for admin action',
    'complaints pending assignment',
    'anything waiting for me to review',
    'what is in the queue',
    'how many new complaints came in',
    'how many need assigning',
    'how many still need to be assigned',
    'what still needs to be assigned',
    'what has come in recently',
    'what have i not reviewed yet',
    'anything new that needs my attention',
    'what is sitting in the queue',
    'what needs my approval',
    'what is waiting for me',
    'what is waiting on me',
    'what is sitting with me',
    'what needs me to look at it',
  ],

  'data.stats.workload': [
    'what should i work on next',
    'what should i prioritise',
    'what is my workload',
    'what do i need to do',
    'give me my priorities',
    'what is on my plate',
    'what should i focus on',
    'help me prioritise my work',
    'what is most important right now',
    'where should i start',
    'what should i tackle first',
    'help me decide what to do first',
    'what is my top priority',
    'what do i deal with first',
    'where do i begin',
    'what needs doing first',
    'help me prioritise',
    'help me prioritise my cases',
    'help me work out what to do first',
    'what should i prioritise today',
    'what is the most important thing for me to do',
    'what is the most important thing to do',
    'whats the single most important task',
  ],

  /* ============================================================
     FAQ
     ============================================================ */

  'faq.submit': [
    'how do i submit a complaint',
    'how to file a complaint',
    'where can i submit a complaint',
    'i want to register a complaint',
    'how do i raise an issue',
    'how to lodge a complaint',
    'i need to report a problem',
    'how do i make a complaint',
    'submit new complaint',
    'file a new complaint',
    'how can i complain',
    'where do i go to complain',
  ],

  'faq.status.meaning': [
    'what do the statuses mean',
    'what does assigned mean',
    'what does under review mean',
    'explain the complaint statuses',
    'what does in progress mean',
    'meaning of status',
    'what are the different statuses',
    'what does submitted mean',
    'explain status types',
    'what is the difference between assigned and in progress',
    'what do these status labels mean',
  ],

  'faq.time': [
    'how long does it take to resolve a complaint',
    'what is the usual resolution time',
    'how long do students normally wait',
    'what is the expected turnaround',
    'how many days does the process take',
    'how long does the whole process take',
    'what is the typical time to resolve complaints',
    'how quickly are complaints handled',
    'typically how many days until something is fixed',
    'how many days until an issue is fixed',
    'usual number of days to fix a complaint',
    'average days to fix an issue',
    'generally how long do these things take',
  ],

  'faq.attachment': [
    'can i attach a file',
    'how do i upload proof',
    'can i add a photo',
    'what files can i upload',
    'attach evidence to complaint',
    'can i upload documents',
    'what file types are allowed',
    'maximum file size',
    'how many files can i attach',
    'am i able to add a picture',
    'can i include a photo with my complaint',
    'am i allowed to upload files',
    'is there a size limit on uploads',
    'what is the file size limit',
  ],

  'faq.anonymous': [
    'can i submit a complaint anonymously',
    'is my complaint anonymous',
    'will my name be visible',
    'can i hide my identity',
    'anonymous complaint',
    'is it confidential',
    'who can see my name',
    'can i complain without revealing who i am',
    'will anyone know it was me',
    'will they know who complained',
    'can i keep my identity private',
    'does my name show up on the complaint',
    'is my identity hidden',
    'can i stay unnamed',
    'can i remain nameless',
    'is it possible to complain unnamed',
    'can my name be left off',
  ],

  'faq.reopen': [
    'can i reopen a complaint',
    'how do i reopen my complaint',
    'my issue came back',
    'the problem is not fixed',
    'reopen a resolved complaint',
    'complaint resolved but issue remains',
    'how to request reopening',
    'the problem happened again',
    'what if the issue returns',
    'it was not really fixed what now',
    'it was not properly fixed what do i do',
    'the fix did not work what now',
    'they closed it but it is not fixed',
  ],

  'faq.feedback': [
    'how do i give feedback',
    'can i rate the resolution',
    'where do i submit feedback',
    'how to rate my complaint',
    'leave a review',
    'give a rating',
    'can i still give feedback',
    'how do i rate the department',
    'how do i leave a score',
    'where do i score the department',
    'how do i submit a score',
    'how do i give a star rating',
  ],

  'faq.track': [
    'how do i track my complaint',
    'where can i see complaint progress',
    'how do i check progress',
    'where do i view my complaints',
    'how to follow my complaint',
    'where is the complaint list page',
    'how can i keep an eye on my complaint',
    'how do i keep track of it',
    'where do i monitor progress',
    'how do i follow up on progress',
    'how do i watch for updates',
  ],

  'faq.categories': [
    'what categories are available',
    'what types of complaints can i submit',
    'which departments can i complain about',
    'list of categories',
    'what can i complain about',
    'available departments',
    'what kind of issues can i report',
    'what sort of issues are covered',
    'what kinds of problems can i report',
    'what subjects can i raise here',
    'what is covered by this system',
    'which topics are supported',
  ],

  'faq.contact': [
    'how do i contact support',
    'who do i talk to',
    'contact details',
    'i need to speak to someone',
    'how to reach the admin',
    'helpline',
    'who can i call',
  ],

  'faq.reject': [
    'what happens if my complaint is rejected',
    'can a complaint be rejected',
    'on what grounds are complaints rejected',
    'why do complaints get rejected',
    'what are the reasons for rejection',
    'can i appeal a rejection',
    'on what basis would a complaint be turned down',
    'what grounds are there for rejection',
    'why would a complaint be declined',
    'when is a complaint refused',
    'what makes a complaint invalid',
    'on what basis would something be rejected',
    'on what basis is a complaint rejected',
    'what would cause a complaint to be rejected',
  ],

  /* ============================================================
     SMALL TALK
     ============================================================ */

  'chat.greeting': [
    'hello', 'hi', 'hey', 'good morning', 'good afternoon', 'good evening',
    'hi there', 'hello there', 'greetings', 'hey there', 'hii', 'helo',
    'good day', 'hello unibot',
  ],

  'chat.thanks': [
    'thank you', 'thanks', 'thanks a lot', 'thank you so much', 'appreciate it',
    'thankyou', 'great thanks', 'awesome thanks', 'cheers', 'perfect thanks',
    'that helps thanks', 'brilliant thank you',
  ],

  'chat.bye': [
    'bye', 'goodbye', 'see you', 'see you later', 'talk to you later',
    // NOTE: deliberately avoids "close"/"closed" and bare "done", which are
    // complaint-status words ("is that complaint closed now") and were
    // pulling genuine status questions into this intent.
    'thats all', 'nothing else', 'exit', 'thats it for now', 'ok thats all',
    'nothing more', 'ok bye then', 'nothing further',
    // NOTE: no "everything" phrases here. "Everything" is a strong content
    // word for listing intents ("show everything that is done"), and having
    // it on both sides pulled genuine questions into this intent.
    'thanks bye', 'no more questions',
    'that is all', 'that will be all', 'ok that is all', 'alright thats all',
  ],

  'chat.help': [
    'help', 'what can you do', 'what can i ask you', 'how can you help me',
    'what do you do', 'options', 'menu', 'show me what you can do',
    'who are you', 'what are you', 'what questions can i ask',
    'give me some examples', 'how do i use this',
    'what sort of things can i ask you', 'tell me what you are capable of',
    'what are you able to do', 'what topics can you help with',
    'list what you can do', 'what is your purpose', 'how can you assist me',
    'give me a rundown of what you do', 'what are your abilities',
    'run through what you can do', 'summarise what you offer',
    'what sort of things can i ask',
    'what things can i ask you',
    'what kind of questions can i ask',
  ],

  /**
   * Out-of-domain examples. NLP.js treats "None" as the catch-all
   * intent, so training it explicitly stops general-knowledge
   * questions being force-fitted into the nearest complaint intent.
   */
  None: [
    'what is the capital of france', 'what is the capital of pakistan',
    'what is the weather today', 'what is the weather in lahore',
    'will it rain tomorrow', 'tell me a joke', 'sing me a song',
    'what is 2 plus 2', 'calculate 15 times 3', 'who is the president',
    'who won the match', 'what is the cricket score', 'what time is it',
    'what is your favourite colour', 'do you like pizza',
    'write me an essay', 'what is the meaning of life', 'how old are you',
    'where do you live', 'book me a flight', 'play some music',
    'what is javascript', 'define photosynthesis', 'who invented the telephone',
    'how tall is mount everest', 'recommend me a movie', 'what should i eat today',
    'tell me about world war two', 'how do i cook biryani',
    'how do i make a cup of tea', 'how do i cook pasta',
    'recommend a good restaurant nearby', 'suggest a place to eat',
    'what movies are out right now', 'how do i change a tyre',
    'what is the exchange rate today', 'tell me a story',
    'who is your favourite cricketer', 'what is the population of multan',
    'how do i learn python', 'give me directions to the airport',
    'translate good morning into urdu', 'how do you say hello in spanish',
    'translate this sentence for me', 'what does bonjour mean',
    'how many calories are in an apple', 'who directed titanic',
    'what is the tallest mountain', 'convert 10 kilometres to miles',
  ],
};

/**
 * Static answers for FAQ and small talk.
 * Arrays mean "pick one at random" so replies do not feel canned.
 */
const answers = {
  'faq.submit': [
    'To submit a complaint, open **Submit Complaint** from the top menu, choose a category and the concerned department, describe the issue in at least 20 characters, then press Submit. You can attach up to 5 files as proof.',
  ],
  'faq.status.meaning': [
    'Here is what each status means:\n• **Submitted** — received, waiting for admin review\n• **Under Review** — an admin is verifying it\n• **Assigned** — accepted and given to a department coordinator\n• **In Progress** — the coordinator is actively working on it\n• **Resolved** — the issue has been fixed\n• **Rejected** — found invalid, and a reason is always recorded\n• **Reopen Requested** — you asked for a resolved complaint to be looked at again',
  ],
  'faq.time': [
    'Most complaints are reviewed within 1–2 working days and then assigned to a coordinator. Resolution time after that depends on the department and the priority the admin sets. Ask me "how long has my complaint been open" for the actual figures on yours.',
  ],
  'faq.attachment': [
    'Yes — you can attach up to **5 files** when submitting a complaint. Allowed types are JPG, PNG, PDF and Word documents, with a maximum of 5 MB per file.',
  ],
  'faq.anonymous': [
    'Yes. Tick the **Submit anonymously** box on the complaint form and your name, email and registration number stay hidden from staff. You will still see your own complaint normally and can still track it here.',
  ],
  'faq.reopen': [
    'If a complaint was marked Resolved but the problem came back, open it from your dashboard, scroll to **Need more help?**, write the reason and press Request Reopen. An admin will then review the request.',
  ],
  'faq.feedback': [
    'Once a complaint is Resolved or Rejected, open it from your dashboard and you will see a feedback section. Give a rating out of 5, pick a satisfaction level, and optionally leave a comment.',
  ],
  'faq.track': [
    'You can track everything from **My Complaints** on your dashboard — or just ask me. Try "is my complaint resolved" or "show my pending complaints".',
  ],
  'faq.categories': [
    'You can complain about: Academics, Facilities, Administration, IT Services, Examination, Transport, Hostel and Fee/Accounts. Each is routed to the matching department, such as the IT Department, Examination Department or Hostel Office.',
  ],
  'faq.contact': [
    'For anything urgent, contact the administration office directly. Otherwise submitting a complaint here is the fastest route — every complaint is seen by an admin and assigned to the responsible department coordinator.',
  ],
  'faq.reject': [
    'An admin can reject a complaint if it is invalid, a duplicate, or outside the university\'s scope. A written reason is always recorded, and you can see it by opening the complaint from your dashboard. If you disagree, you can submit a new complaint with more detail and evidence.',
  ],
  'chat.greeting': [
    'Hello! I am UniBot, your complaint assistant. Ask me about your complaints or how the system works.',
    'Hi there! Need an update on a complaint, or help with something?',
    'Hello! How can I help you today?',
  ],
  'chat.thanks': [
    'You are welcome! Anything else I can help with?',
    'Happy to help. Let me know if you need anything else.',
    'Any time! Feel free to ask me another question.',
  ],
  'chat.bye': [
    'Goodbye! You can reopen this chat any time from the button in the corner.',
    'Take care! I am here whenever you need an update.',
  ],
};

/** Shown when confidence is too low to trust a match. */
const fallbacks = [
  'I did not quite catch that.',
  'Sorry, I am not sure about that one.',
  'I did not understand that fully.',
];

module.exports = { intents, answers, fallbacks };
